#! /bin/bash

set -u

KUBEMARK_CLUSTER_RESOURCE_GROUP="${KUBEMARK_CLUSTER_RESOURCE_GROUP:-kubemark-cluster}"
EXTERNAL_CLUSTER_RESOURCE_GROUP="${EXTERNAL_CLUSTER_RESOURCE_GROUP:-kubemark-external-cluster}"

LOCATION="${LOCATION:-southcentralus}"

PRIVATE_KEY="${PRIVATE_KEY:-${HOME}/.ssh/id_rsa}"

KUBEMARK_SIZE="${KUBEMARK_SIZE:-100}"
